### ISSUE TITLE
[BUG] Error in UTL 1.1.0-pre1

### ISSUE THREAD

**Issue by AsyrafFile** [Tudi20/Universal-THCRAP-Launcher#39]
When opening UTL after opening I received this error
`************** Exception Text **************
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at Universal_THCRAP_Launcher.MainForm.PopulatePatchList()
   at Universal_THCRAP_Launcher.MainForm.Form1_Load(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)`

Opening the setting also giving me the message
`************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at Universal_THCRAP_Launcher.MainForm.PopulatePatchList()
   at System.Windows.Forms.CheckBox.OnCheckedChanged(EventArgs e)
   at System.Windows.Forms.CheckBox.set_CheckState(CheckState value)
   at System.Windows.Forms.CheckBox.set_Checked(Boolean value)
   at Universal_THCRAP_Launcher.SettingsForm.SettingsForm_Load(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)`

The patch list and program list is empty. 
![image](https://user-images.githubusercontent.com/40899099/58836422-5ff55300-868b-11e9-9bac-b40d9e722d8b.png)

Unchecking hide extension fix the list
![image](https://user-images.githubusercontent.com/40899099/58836560-b1054700-868b-11e9-8989-9d40a1bfbcd6.png)

Language selection also gave me the error message
`************** Exception Text **************
System.ArgumentNullException: Value cannot be null.
Parameter name: path
   at System.IO.File.ReadAllText(String path)
   at Universal_THCRAP_Launcher.I18N.UpdateLangResource(String filePath)
   at Universal_THCRAP_Launcher.SettingsForm.languageComboBox_SelectedIndexChanged(Object sender, EventArgs e)
   at System.Windows.Forms.ComboBox.OnSelectedIndexChanged(EventArgs e)
   at System.Windows.Forms.ComboBox.WmReflectCommand(Message& m)
   at System.Windows.Forms.ComboBox.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)`

Naming type also gave me error message but fixed the game list
![image](https://user-images.githubusercontent.com/40899099/58836931-b31bd580-868c-11e9-9c55-10daabe3a323.png)

`************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at Universal_THCRAP_Launcher.MainForm.PopulateGames()
   at System.Windows.Forms.ComboBox.OnSelectedIndexChanged(EventArgs e)
   at System.Windows.Forms.ComboBox.WmReflectCommand(Message& m)
   at System.Windows.Forms.ComboBox.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)`

**Comment by AsyrafFile** [comment]
Sort button is not working.

**Comment by lilyremigia** [comment]
Fixed in 9899eb37f1feffb62cc5dcf41de5718e7a0ae5f7
