### ISSUE TITLE
[BUG] Error on launch, forms not populated

### ISSUE THREAD

**Issue by WindowDump** [Tudi20/Universal-THCRAP-Launcher#4]
Using the latest version of the launcher, on launching the application, an error dialog appears. If continue is selected, the forms on the main application display are not populated. This error does not occur on the second most recent release.

```
************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at Universal_THCRAP_Launcher.Form1.Form1_Load(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

Also as long as I'm making this report, remember to remove ``uthcrapl_confis.js`` from the list of patch configurations.

**Comment by lilyremigia** [comment]
Fixed in commit a834a7ccfd2a4f9e6aa0e648441c91084603bdf2
