### ISSUE TITLE
[BUG] Crash when selecting patch

### ISSUE THREAD

**Issue by lilyremigia** [Tudi20/Universal-THCRAP-Launcher#5]
**Describe the bug**
[2019.01.17. 21:30] Youmu Konpaku: hey, Tudi, whenever I use the universal launcher, i get this message whenever i select a game or patch:

**Crash**
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Universal_THCRAP_Launcher.Form1.SelectedIndexChanged(Object sender, EventArgs e)
   at System.Windows.Forms.ListBox.OnSelectedIndexChanged(EventArgs e)
   at System.Windows.Forms.ListBox.WmReflectCommand(Message& m)
   at System.Windows.Forms.ListBox.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)```

**Comment by lilyremigia** [comment]
Commit 91ced423996f171e48444fe999cb8b344a6af993 hopefully fixed it.
